-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 10:24:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE `country` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` char(2) NOT NULL COMMENT 'Two-letter country code (ISO 3166-1 alpha-2)',
  `name` varchar(64) NOT NULL COMMENT 'English country name',
  `full_name` varchar(128) NOT NULL COMMENT 'Full English country name',
  `iso3` char(3) NOT NULL COMMENT 'Three-letter country code (ISO 3166-1 alpha-3)',
  PRIMARY KEY (`country_id`),
  UNIQUE KEY `name` (`code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;


INSERT INTO `eucountries` VALUES ('1', 'AL', 'Albania', 'Republic of Albania', 'ALB');
INSERT INTO `eucountries` VALUES ('2', 'AN', 'Netherlands Antilles', 'Netherlands Antilles', 'ANT');
INSERT INTO `eucountries` VALUES ('3', 'AT', 'Austria', 'Republic of Austria', 'AUT');
INSERT INTO `eucountries` VALUES ('4', 'BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH');
INSERT INTO `eucountries` VALUES ('5', 'BE', 'Belgium', 'Kingdom of Belgium', 'BEL');
INSERT INTO `eucountries` VALUES ('6', 'BG', 'Bulgaria', 'Republic of Bulgaria', 'BGR');
INSERT INTO `eucountries` VALUES ('7', 'CH', 'Switzerland', 'Swiss Confederation', 'CHE');
INSERT INTO `eucountries` VALUES ('8', 'CZ', 'Czech Republic', 'Czech Republic', 'CZE');
INSERT INTO `eucountries` VALUES ('9', 'DE', 'Germany', 'Federal Republic of Germany', 'DEU');
INSERT INTO `eucountries` VALUES ('10', 'DK', 'Denmark', 'Kingdom of Denmark', 'DNK');
INSERT INTO `eucountries` VALUES ('11', 'EE', 'Estonia', 'Republic of Estonia', 'EST');
INSERT INTO `eucountries` VALUES ('12', 'ES', 'Spain', 'Kingdom of Spain', 'ESP');
INSERT INTO `eucountries` VALUES ('13', 'FI', 'Finland', 'Republic of Finland', 'FIN');
INSERT INTO `eucountries` VALUES ('14', 'FR', 'France', 'French Republic', 'FRA');
INSERT INTO `eucountries` VALUES ('15', 'GB', 'United Kingdom', 'United Kingdom of Great Britain & Northern Ireland', 'GBR');
INSERT INTO `eucountries` VALUES ('16', 'GE', 'Georgia', 'Georgia', 'GEO');
INSERT INTO `eucountries` VALUES ('17', 'GL', 'Greenland', 'Greenland', 'GRL');
INSERT INTO `eucountries` VALUES ('18', 'GR', 'Greece', 'Hellenic Republic Greece', 'GRC');
INSERT INTO `eucountries` VALUES ('19', 'HR', 'Croatia', 'Republic of Croatia', 'HRV');
INSERT INTO `eucountries` VALUES ('20', 'HU', 'Hungary', 'Republic of Hungary', 'HUN');
INSERT INTO `eucountries` VALUES ('21', 'IE', 'Ireland', 'Ireland', 'IRL');
INSERT INTO `eucountries` VALUES ('22', 'IT', 'Italy', 'Italian Republic', 'ITA');
INSERT INTO `eucountries` VALUES ('23', 'LT', 'Lithuania', 'Republic of Lithuania', 'LTU');
INSERT INTO `eucountries` VALUES ('24', 'LU', 'Luxembourg', 'Grand Duchy of Luxembourg', 'LUX');
INSERT INTO `eucountries` VALUES ('25', 'LV', 'Latvia', 'Republic of Latvia', 'LVA');
INSERT INTO `eucountries` VALUES ('26', 'MA', 'Morocco', 'Kingdom of Morocco', 'MAR');
INSERT INTO `eucountries` VALUES ('27', 'MC', 'Monaco', 'Principality of Monaco', 'MCO');
INSERT INTO `eucountries` VALUES ('28', 'MD', 'Moldova', 'Republic of Moldova', 'MDA');
INSERT INTO `eucountries` VALUES ('29', 'ME', 'Montenegro', 'Republic of Montenegro', 'MNE');
INSERT INTO `eucountries` VALUES ('30', 'MK', 'Macedonia', 'Republic of Macedonia', 'MKD');
INSERT INTO `eucountries` VALUES ('31', 'MT', 'Malta', 'Republic of Malta', 'MLT');
INSERT INTO `eucountries` VALUES ('32', 'NL', 'Netherlands', 'Kingdom of the Netherlands', 'NLD');
INSERT INTO `eucountries` VALUES ('33', 'NO', 'Norway', 'Kingdom of Norway', 'NOR');
INSERT INTO `eucountries` VALUES ('34', 'PL', 'Poland', 'Republic of Poland', 'POL');
INSERT INTO `eucountries` VALUES ('35', 'PT', 'Portugal', 'Portuguese Republic', 'PRT');
INSERT INTO `eucountries` VALUES ('36', 'RO', 'Romania', 'Romania', 'ROU');
INSERT INTO `eucountries` VALUES ('37', 'RS', 'Serbia', 'Republic of Serbia', 'SRB');
INSERT INTO `eucountries` VALUES ('38', 'RU', 'Russian Federation', 'Russian Federation', 'RUS');
INSERT INTO `eucountries` VALUES ('39', 'SE', 'Sweden', 'Kingdom of Sweden', 'SWE');
INSERT INTO `eucountries` VALUES ('40', 'SI', 'Slovenia', 'Republic of Slovenia', 'SVN');
INSERT INTO `eucountries` VALUES ('41', 'SK', 'Slovakia', 'Slovakia (Slovak Republic)', 'SVK');
INSERT INTO `eucountries` VALUES ('42', 'SM', 'San Marino', 'Republic of San Marino', 'SMR');
INSERT INTO `eucountries` VALUES ('43', 'TR', 'Turkey', 'Republic of Turkey', 'TUR');
INSERT INTO `eucountries` VALUES ('44', 'UA', 'Ukraine', 'Ukraine', 'UKR');
INSERT INTO `eucountries` VALUES ('45', 'VA', 'Vatican City', 'Holy See (Vatican City State)', 'VAT');

-- -----------------------------------------------------
-- Table `mydb`.`toernooi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toernooi` (
  `id` INT NOT NULL,
  `jaar` VARCHAR(45) NULL,
  `gastland(en)` VARCHAR(255) NULL,
  `toernooicode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wedstrijd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wedstrijd` (
  `idWedstrijd` INT NOT NULL,
  `Time` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  `country_id1` INT NOT NULL,
  `toernooi_id` INT NOT NULL,
  `thuis` INT(2) NULL,
  `uit` VARCHAR(45) NULL,
  PRIMARY KEY (`idWedstrijd`, `country_id`, `country_id1`, `toernooi_id`),
  INDEX `fk_Wedstrijd_country1_idx` (`country_id` ASC),
  INDEX `fk_Wedstrijd_country2_idx` (`country_id1` ASC),
  INDEX `fk_Wedstrijd_toernooi1_idx` (`toernooi_id` ASC),
  CONSTRAINT `fk_Wedstrijd_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wedstrijd_country2`
    FOREIGN KEY (`country_id1`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wedstrijd_toernooi1`
    FOREIGN KEY (`toernooi_id`)
    REFERENCES `mydb`.`toernooi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `toernooi` (`id`, `jaar`, `gastland(en)`, `toernooicode`) VALUES ('1', '2016', 'Frankrijk', 'Ek');
